package com.carsharing.backend.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "document_info") // This makes it a top-level document
public class DocumentInfo {

    @Id
    private String id;
    private String userId; // ID of the User this document belongs to
    private String documentType; // e.g., "DRIVING_LICENSE", "VEHICLE_REGISTRATION"
    private String originalFilename;
    private String contentType; // MIME type
    private long size; // File size in bytes
    private String filePath; // Stores the unique filename generated by FileStorageService
    private LocalDateTime uploadedAt;
    private DocumentStatus status; // Uses the DocumentStatus ENUM

    // Optional fields you might add later:
    // private String adminVerifierId;
    // private LocalDateTime processedAt;
    // private String rejectionReason;

    public void setStoredFilename(String filename) { this.originalFilename = filename; }
    public void setUploadTimestamp(LocalDateTime uploadTimestamp) { this.uploadedAt = uploadTimestamp; }
    public void setVerificationStatus(DocumentStatus status) { this.status = status; }
}