package com.carsharing.backend.dto; // Make sure this package exists or adjust as needed

import java.util.List;

// Using Lombok can significantly reduce boilerplate code.
// If you have Lombok configured, you can uncomment these and remove the manual methods:
// import lombok.Data;
// import lombok.AllArgsConstructor;
// import lombok.NoArgsConstructor;

// @Data // Generates getters, setters, toString, equals, hashCode
// @AllArgsConstructor // Generates a constructor with all fields
// @NoArgsConstructor // Generates a no-argument constructor
public class UserDTO {

    private String id;
    private String name;
    private String email;
    private List<String> roles;
    private String driverStatus;
    // Note: We are intentionally EXCLUDING the 'password' field.
    // Note: We are EXCLUDING the 'documents' field for the general list view
    //       to keep the payload smaller. If the list needs document info, add it back.

    // --- Manual Constructor (if not using Lombok's @AllArgsConstructor) ---
    public UserDTO(String id, String name, String email, List<String> roles, String driverStatus) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.roles = roles;
        this.driverStatus = driverStatus;
    }

    // --- Manual No-Argument Constructor (if not using Lombok's @NoArgsConstructor) ---
    // Often required by frameworks like Jackson, although primarily for deserialization.
    public UserDTO() {
    }

    // --- Manual Getters (if not using Lombok's @Data) ---
    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public List<String> getRoles() {
        return roles;
    }

    public String getDriverStatus() {
        return driverStatus;
    }

    // --- Manual Setters (if not using Lombok's @Data) ---
    // Generally good practice to include, though not strictly necessary if
    // you only construct the DTO and don't modify it afterwards.
    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setRoles(List<String> roles) {
        this.roles = roles;
    }

    public void setDriverStatus(String driverStatus) {
        this.driverStatus = driverStatus;
    }

    // --- Optional: toString(), equals(), hashCode() (if not using Lombok's @Data) ---
    // Useful for debugging and collections, but not strictly required for basic DTO function.
    @Override
    public String toString() {
        return "UserDTO{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", roles=" + roles +
                ", driverStatus='" + driverStatus + '\'' +
                '}';
    }

    // equals() and hashCode() implementations omitted for brevity
    // but would typically be included or generated by Lombok/IDE
}